version: '3'

services:
  db:
    image: 'docker.io/library/postgres:13'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
